version: "3.7"

services:
  database_vshop:
    image: postgres
    container_name: database_vshop
    restart: always
    expose:
      - 5432:5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=vshop
      - POSTGRES_DB=vshop
    volumes:
      - pgdata:/data/postgres
  app:
    build: 
      dockerfile: Dockerfile
      context: .
    container_name: api_vshop
    command: npm run start:migrate
    env_file: .env
    depends_on:
      - database_vshop
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
  frontend_vshop:
    build:
      dockerfile: Dockerfile
      context: ../vehicle-shop-frontend
    container_name: frontend_vshop
    depends_on:
      - app
    expose:
      - 3000
    ports:
      - 3000:3000
volumes:
  pgdata:
    driver: local
