version: "3.7"

services:
  database_vshop:
    image: postgres
    container_name: database_vshop
    restart: always
    expose:
      - 5432:5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=vshop
      - POSTGRES_DB=vshop
    volumes:
      - pgdata:/data/postgres
  db-migrations:
    image: backend
    command: npx prisma migrate dev
    depends_on:
      - database_vshop
    profiles:
      - tools
  app:
    build: .
    container_name: api_vshop
    command: npm run start:migrate
    env_file: .env
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app

volumes:
  pgdata:
    driver: local
